### ISSUE TITLE
Multiple configurations and webpack-dev-server

### ISSUE THREAD

**Issue by aeyoll** [symfony/webpack-encore#113]
Hello guys,
One use case of the multiple webpack configurations can be for instance to have a bundle for a frontend app, and another for a backend app on the same Symfony project. If I set different output paths in each config, and using the packages assets configuration to specify two manifest.json files, I'm able to make it work using the ```encore dev``` command.

```
framework:
  assets:
    packages:
        frontend:
          json_manifest_path: '%kernel.project_dir%/web/build/frontend/manifest.json'
        backend:
          json_manifest_path: '%kernel.project_dir%/web/build/backend/manifest.json'
```

However, when I try to use the webpack-dev-server, it looks like it's trying to serve the content from the first webpack configuration, making it impossible to use:

```
> encore dev-server --hot --port 8001

Running webpack-dev-server ...

Project is running at http://localhost:8001/
webpack output is served from /build/frontend/
```

Maybe one way to solve it would be to set an option to specify the output directory for the dev-server, but I don't think it exists at the moment.

Here is my encore configuration:

```
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
  .setOutputPath('web/build/frontend/')
  .setPublicPath('/build/frontend')
  .cleanupOutputBeforeBuild()
  .addEntry('app', './assets/js/frontend/main.js')
  .createSharedEntry('vendor', [
    ...
  ])
  .addStyleEntry('global', './assets/css/frontend/global.scss')
  .enableSassLoader()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction());

const frontendConfig = Encore.getWebpackConfig();

Encore.reset();

Encore
  .setOutputPath('web/build/backend/')
  .setPublicPath('/build/backend')
  .createSharedEntry('vendor', [
    ...
  ])
  .addEntry('app', './assets/js/backend/main.js')
  .addStyleEntry('global', './assets/css/backend/global.scss')
  .enableSassLoader()
  .enableSourceMaps(!Encore.isProduction())
  .enableVersioning(Encore.isProduction());

// build the second configuration
const backendConfig = Encore.getWebpackConfig();

module.exports = [frontendConfig, backendConfig];
```

Thanks a lot
