### ISSUE TITLE
CSS variables are wrongly optimized in production

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/webpack-encore#436]
In a CSS file I define several CSS variables, including these:

```css
:root {
    --border-width: 1px;
    --border-style: solid;
    --border-color: #e3e7ee;
}
```

When using `yarn encore dev` everything is great ... but with `yarn encore production` those 3 variables are destroyed and instead, the following wrong CSS is generated:

```css
:root {
    border:1px solid #e3e7ee
}
```

How can I tell Webpack Encore to not optimize my CSS variables? Thanks!
