### ISSUE TITLE
Document how to use versioned images in css (scss)

### ISSUE THREAD

**Issue by luckylooke** [symfony/webpack-encore#589]
Documentation
https://symfony.com/doc/current/frontend/encore/copy-files.html
cases mentioned: using versioned images in js, in twig
cases not mentioned: using versioned images in styles (css/scss..)

example.scss
`background: url(../images/bg.jpg);`

It seems that they should work out of the box.. but problem is when you save background url in scss variable and distribute all over the modules... it is resolved in each module separately and it fails on error that it cannot found module... of course because relative path from each module is different... I was trying to solve it with alias and `~` prefix.. but process seems to be removing `~` from path and trying to resolve it then without it.. which of course fails again.

So I am wondering what is recommended way to have scss url defined in one place and used over any modules in project regarding standard webpack-encore setup.

We are using vue, but I think this is more general question applying also on other frameworks.

Thank you for your time!
Ctibor

**Comment by Kocal** [comment]
Hum that's a good question, I've never faced this issue before.
What happens if you try to prefix with `/`?

**Comment by Lyrkan** [comment]
Hi @luckylooke,

I'm not sure to understand what you're trying to do... would you be able to share a small repository that shows the issue you're facing?

Also, if you're using Scss maybe you could try disabling the `resolve-url-loader` when calling `Encore.enableSassLoader()`?

https://github.com/symfony/webpack-encore/blob/b8f08a529900ae887841e96eee6115a9a185bddf/index.js#L750-L756

**Comment by Kocal** [comment]
If I understand correctly, he has at least 4 files:
- `assets/images/bg.jpg`, the background image
- `assets/css/_variables.scss` which contains:
```scss
$bg-var: background: url(../images/bg.jpg);
```
- `assets/css/file.scss` which contains:
```scss
@import "variables"

body { background: $bg-var } // resolves to "../images/bg.jpg" and it's fine
```
- `assets/css/foo/bar/file.scss` which contains:
```scss
@import "../../variables"

body { background: $bg-var } // resolves to "../images/bg.jpg" but the image is not here
```

But maybe I'm wrong?
