### ISSUE TITLE
Run Encore dev-server from a docker container

### ISSUE THREAD

**Issue by claytron5000** [symfony/webpack-encore#821]
There's a similar issue here https://github.com/symfony/webpack-encore/issues/366, but I want to provide details specific to the use-case I'm attempting.

Goal:
Run a dockerized Symfony application with a React front-end locally with hot-module reloading enabled.

Problem:
When running the two servers in containers (web server, webpack dev server), the dev server doesn't serve its files.

Foreshortened `docker-compose.yml`

```
services:
    nginx:
        build: ./docker/nginx
        ports:
            - "8090:80"
            - "8043:443"
        depends_on:
            - php
        networks:
            - blackfire
            - php
        volumes:
            - .:/var/www:cached
            - shared-volume:/var/www/public/files
    node:
        image: node:10-alpine
        volumes:
            - .:/var/www/symfony:consistent
        working_dir: /var/www/symfony
```
webpack.config.js

```
Encore
    .setOutputPath('public/build/')
    .setPublicPath('/build')

    .addEntry('app', './assets/js/app.js')
    .addStyleEntry('style', './assets/css/app.css')
    .enablePostCssLoader()

    .splitEntryChunks()

    .disableSingleRuntimeChunk()

    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;
    })

    .enableReactPreset();
```
twig template
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('style') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </body>
</html>
```
The commands:
```
# docker-compose up
#  docker-compose run node yarn encore dev-server --hot
yarn run v1.22.4
$ /var/www/symfony/node_modules/.bin/encore dev-server --hot
Running webpack-dev-server ...

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from http://localhost:8080/build/
ℹ ｢wds｣: Content not from webpack is served from /var/www/symfony/public
ℹ ｢wds｣: 404s will fallback to /index.html
 DONE  Compiled successfully in 4393ms
```
That all looks good to me, but when I load `localhost:8090` I get `Loading failed for the <script> with source “http://localhost:8080/build/app.js”` errors for each resource. When I navigate to anywhere on localhost:8080 I get no server as well.

I *think* the usual solution to this is to serve the dev-server with a `0.0.0.0` host: `docker-compose run node yarn encore dev-server --hot --host 0.0.0.0`, but that doesn't change the situation, and the files are not available on `localhost:8080`,
