### ISSUE TITLE
Incorrect paths for fonts

### ISSUE THREAD

**Issue by nikrou** [symfony/webpack-encore#88]
My context:
I host my webiste under a given path. I do not use symfony but we don't care here.
I used (of course) webpack-encore to manage my assets. It works well except for fonts because of my extra path.

My website is hosted under /my-path. I generate my stylesheets using sass. Stylesheets paths are composed of my base path and the path found in manifest.json.
I've got for example  /my-path/build/css/style.css
I use font-awesome to add web-fonts. The url() in the generated stylesheets is url(/build/fonts/fontawesome-webfont.eot); and so one.
I don't know (just start to investigate) how to fix it. I usually used webpack (without webpack-encore) and webpack used a relative path to fonts from stylesheets instead of an absolute path; something like:

```css
@font-face {
  font-family: 'FontAwesome';
  src: url(./fonts/fontawesome-webfont.eot);
  src: url(./fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format("embedded-opentype"), url(./fonts/fontawesome-webfont.woff2) format("woff2"), url(./fonts/fontawesome-webfont.woff) format("woff"), url(./fonts/fontawesome-webfont.ttf) format("truetype"), url(./images/fontawesome-webfont.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```

And I've got 

```css
@font-face {
  font-family: 'FontAwesome';
  src: url(/my/public/conf/path/build/fonts/fontawesome-webfont.eot);
  src: url(/my/public/conf/path/build/fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format("embedded-opentype"), url(/my/public/conf/path/build/fonts/fontawesome-webfont.woff2) format("woff2"), url(/my/public/conf/path/build/fonts/fontawesome-webfont.woff) format("woff"), url(/my/public/conf/path/build/fonts/fontawesome-webfont.ttf) format("truetype"), url(/my/public/conf/path/build/images/fontawesome-webfont.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Any idea to solve that issue is appreciate. If you have any question, don't hesitate.

**Comment by weaverryan** [comment]
Hey @nikrou!

Hmm. Could you post your `webpack.config.js` file? I'm specifically curious what your `setPublicPath()` looks like - things are done a little bit different under a subdirectory (http://symfony.com/doc/current/frontend/encore/faq.html#my-app-lives-under-a-subdirectory).

Cheers!

**Comment by nikrou** [comment]
@weaverryan 

my config file:
```js
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('./build/')
    .setPublicPath('/themes/default/build')
    .cleanupOutputBeforeBuild()
    .addEntry('js/index', './src/js/index.js')
    .addStyleEntry('css/style', './src/scss/style.scss')
    .enableSassLoader()
    .autoProvidejQuery()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```
I used manifest.json:
```json
{
  "themes/default/build/css/style.css": "/themes/default/build/css/style.css",
  "themes/default/build/fonts/fontawesome-webfont.eot?v=4.7.0": "/themes/default/build/fonts/fontawesome-webfont.eot",
  "themes/default/build/fonts/fontawesome-webfont.ttf?v=4.7.0": "/themes/default/build/fonts/fontawesome-webfont.ttf",
  "themes/default/build/fonts/fontawesome-webfont.woff2?v=4.7.0": "/themes/default/build/fonts/fontawesome-webfont.woff2",
  "themes/default/build/fonts/fontawesome-webfont.woff?v=4.7.0": "/themes/default/build/fonts/fontawesome-webfont.woff",
  "themes/default/build/images/fontawesome-webfont.svg?v=4.7.0": "/themes/default/build/images/fontawesome-webfont.svg",
  "themes/default/build/js/index.js": "/themes/default/build/js/index.js"
}
```
And I generate the link:
```html
<link rel="stylesheet" href="/my-path/themes/default/build/css/style.css">
```
The main problem is that my style.css file contains absolute link to font awesome files:
```css
@font-face {
  font-family: 'FontAwesome';
  src: url(/themes/default/build/fonts/fontawesome-webfont.eot);
  src: url(/themes/default/build/fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format("embedded-opentype"), url(/themes/default/build/fonts/fontawesome-webfont.woff2) format("woff2"), url(/themes/default/build/fonts/fontawesome-webfont.woff) format("woff"), url(/themes/default/build/fonts/fontawesome-webfont.ttf) format("truetype"), url(/themes/default/build/images/fontawesome-webfont.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```
I read documentation about setManifestPrefix method but it only changes manifest.json. It's not related with my issue.
I will generated a plain webpack config file without encore and diff with that one to help you understand, if you want.

**Comment by nikrou** [comment]
I wish I could have something like that in my style.css file:
```css
@font-face {
  font-family: 'FontAwesome';
  src: url(../fonts/fontawesome-webfont.eot);
  src: url(../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format("embedded-opentype"), url(../fonts/fontawesome-webfont.woff2) format("woff2"), url(../fonts/fontawesome-webfont.woff) format("woff"), url(../fonts/fontawesome-webfont.ttf) format("truetype"), url(./build/images/fontawesome-webfont.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```
That css part can be generated with the following file-loader config:
```js
 {
	test: /\.(woff|woff2|ttf|eot|otf)$/,
	loader: 'file-loader',
	options: {
           name: 'fonts/[name].[ext]',
	   publicPath: '../'
	}
 }
```
But webpack-encore use something like that:
```js
{
   test: /\.(woff|woff2|ttf|eot|otf)$/,
   loader: 'file-loader',
   options: { 
      name: 'fonts/[name].[ext]',
      publicPath: '/themes/default/build/' 
   }
}
```
I don't find a way to override webpack-encore default configuration for module rules.
I know the idea of webpack-encore is to use webpack without pain and it makes the job. What's a good tool. But it would be great if the configuration can be tweak.

**Comment by weaverryan** [comment]
Thanks for the details!

Try this:

```js
var Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('./build/')
    .setPublicPath('/my-path/themes/default/build')
    .setManifestKeyPrefix('themes/default/build')

    // ... everything else the same
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

The issue is that your `setPublicPath` isn't correct. Because you're under a sub-directory, your *true* public path is `/my-path/themes/default/build`. You need to tell webpack your *actual*, true public path because (in some cases - specifically something called code splitting) - webpack needs to be able to make AJAX requests back for assets (and it uses the publicPath to know where those live).

This should fix your problem - it will dump something like this:

```css
@font-face {
  font-family: 'FontAwesome';
  src: url(/my-path/themes/default/build/fonts/fontawesome-webfont.eot);
  src: url(/my-path/themes/default/build/fonts/fontawesome-webfont.eot?#iefix&v=4.7.0) format("embedded-opentype"), url(/my-path/themes/default/build/fonts/fontawesome-webfont.woff2) format("woff2"), url(/my-path/themes/default/build/fonts/fontawesome-webfont.woff) format("woff"), url(/my-path/themes/default/build/fonts/fontawesome-webfont.ttf) format("truetype"), url(/my-path/themes/default/build/images/fontawesome-webfont.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```

It shouldn't matter to us whether these paths are absolute or relative - so I wouldn't worry about that detail. Webpack just makes sure that these paths are *correct* - as long as you give it the correct public path :).

Let me know if this fixes things!
