### ISSUE TITLE
image uri-s in scss files after encore 1.0

### ISSUE THREAD

**Issue by mmarton** [symfony/webpack-encore#896]
Hi!

I just upgraded to 1.0 and have a question about image uri-s in scss files.

I don't know why, but having absolute uri in scss files was somehow working in 0.33
```scss
// assets/scss/app.scss
.logo {
    background: url(/bundles/admin/img/logo.png);
}
```
logo.png is symlinked from vendor

after 1.0 I had to change the url to url(../../public/bundles/admin/img/logo.png)

which is fine just gets uglier after some subfolder

Is there something I missed during update or is it an expected BC?
